# Generated by Django 5.1.6 on 2025-03-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='content',
            new_name='title',
        ),
    ]
